### PR TITLE
fix(core): restore ta.<category> attribute access, lazily

### PR DESCRIPTION
**Pull request by rmarcink**
## Problem

On a fresh interpreter, 8 of the 10 category subpackages are not reachable as attributes:

```python
>>> import pandas_ta_classic as ta
>>> ta.momentum
AttributeError: module 'pandas_ta_classic' has no attribute 'momentum'
```

Same for `overlap`, `trend`, `volume`, `statistics`, `candles`, `cycles`, `math`. Only `volatility` and `performance` resolve.

Worse, it is **order-dependent** — the attribute appears once anything happens to import that subpackage:

```
before any indicator call:  hasattr(ta, "momentum") -> False
after df.ta.rsi():          hasattr(ta, "momentum") -> True
```

`docs/quickstart.md` has documented `print(ta.momentum)` as a supported way to list a category since the quickstart guide was first written, and that block has never been edited since.

## This is a regression, not a doc error

I bisected it to `59ccbb4` ("refactor(core): lazy-load AnalysisIndicators and category subpackages"). Before that commit, `core.py` did `from pandas_ta_classic.<category> import *` for all ten categories, so every one of them was eagerly bound onto the package. Measured directly across the two commits, in throwaway worktrees:

| attribute | `59ccbb4^` | `59ccbb4` |
|---|---|---|
| momentum, overlap, trend, volume, statistics, candles, cycles, math | **True** | **False** |
| performance, volatility | True | True |

The two survivors are accidents, not design: `volatility` from an explicit `from . import volatility` in `__init__.py`, `performance` transitively because `utils/_metrics.py` imports `drawdown`/`log_return`/`percent_return` at module scope.

Root cause: CPython binds a submodule onto its parent (`setattr(parent, child, mod)`) as a side effect of the first `import parent.child` anywhere in the process. `_indicator_loader.py:38` imports `pandas_ta_classic.<category>.<indicator>` on demand, so whether `ta.momentum` existed depended entirely on what the caller had run earlier. The package's `__getattr__` had branches for indicator functions and `cdl_*` submodules, but none for category names.

`_lazy_subpackage.py` is not implicated — it governs the `ta.<cat>.<indicator>` namespace and installs no hook on the parent package. The two mechanisms compose: `ta.momentum` returns the `_LazySubpackage`, and `ta.momentum.rsi` then resolves through it.

## Fix

Resolve every category through the existing PEP 562 `__getattr__` and advertise them in `__dir__()`. Four lines plus a comment, on the mechanism the file already uses for ~250 indicator functions.

Deliberately **not** added to `__all__`: that lists the eagerly bound names, and adding the categories would make `from pandas_ta_classic import *` bind `math` and `statistics`, shadowing the stdlib modules of those names in the importer's namespace — the same hazard `_lazy_subpackage.py` already avoids for the `min`/`max`/`sum` aliases. Wildcard-import surface is byte-for-byte identical to `main` (60 names, `volatility` as before).

The eager `from . import volatility` is redundant now and is removed, so `volatility` no longer loads at import time either. The shadowing invariant its comment described is enforced elsewhere — `utils/__init__.py` keeps the `utils.volatility()` metric out of `utils.__all__`. Verified: `ta.volatility` is still the subpackage, `ta.utils.volatility` is still the metric function.

`performance` still loads eagerly through `utils/_metrics.py`. That coupling is pre-existing and unrelated, so it is left alone and called out in the test.

Cold-import time is unaffected — the categories still load on first access. Confirmed structurally (identical import graph: 626 modules, 21 `pandas_ta_classic.*`, same sorted module-name set) and by an interleaved A/B wall-clock run whose distributions overlap entirely.

## Also in this PR

`docs/quickstart.md`'s "List indicators by category" example now uses `ta.Category["momentum"]`. `print(ta.momentum)` only ever printed a module repr, never an indicator list, so that example was wrong on its own terms independently of the AttributeError.

The second commit corrects `CHANGELOG.md`, which claimed "Public API unchanged" for the lazy refactor. That was wrong twice over: the category regression above (unintentional, fixed here) and `from pandas_ta_classic import *` no longer binding the ~250 indicator functions (427 names before `59ccbb4`, 137 immediately after, 60 today). The wildcard-import change is documented as an intentional break rather than reverted — restoring it would work and would even stay lazy, but only by binding `math`, `statistics`, `min`, `max` and `sum` into the importer's namespace. No doc or example in the repo uses a wildcard import.

`59ccbb4` is untagged (latest tag `0.6.52`, two days earlier), so neither break has reached a release.

## Tests

`tests/test_lazy_core.py` gains `TestCategoryAttrAccess`:

- `test_all_categories_in_dir` — every category is advertised by `dir()`.
- `test_category_attr_resolves_without_prior_indicator_access` — runs in a **subprocess**, because an in-process test would be contaminated by earlier tests having already imported categories, and would pass against the buggy code. It asserts the 9 non-eager categories are absent from `sys.modules` immediately after import (guarding the laziness claim), then that all 10 resolve to modules.

Both fail against `main`'s `__init__.py` (verified by stashing the change: `2 failed`, `AssertionError: hasattr failed for candles`).

```
pytest tests/test_lazy_core.py tests/test_accessor_api.py tests/test_accessor_conformance.py tests/test_utils.py  ->  141 passed
black --check --diff pandas_ta_classic/                                                                          ->  317 files unchanged
ruff check pandas_ta_classic --select E9,F63,F7,F82                                                              ->  All checks passed
mypy pandas_ta_classic/                                                                                          ->  Success, 316 source files
```

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by rmarcink** [comment]
Added a third commit: `ta.cdl` was a second casualty of the same refactor.

To be sure the PR was complete, I swept all 427 public names reachable at `59ccbb4^` with one fresh interpreter per name — probing them sequentially in a single process contaminates the result, because each `getattr` imports a subpackage and makes later names visible, which is the very bug under test. Isolated, exactly nine attributes broke at `59ccbb4`:

```
candles, cycles, math, momentum, overlap, statistics, trend, volume, cdl
```

Nothing else. Every indicator function, every `cdl_*` submodule and every util stayed reachable throughout. (67 names are unreachable at `HEAD` versus `59ccbb4^`, but 66 of those were removed by later commits — the deliberate namespace cleanup already recorded in the changelog: `np`, `pd`, `DataFrame`, `Series`, the `npX` aliases and so on.)

`cdl` is the shorthand wrapper defined inside `candles/cdl_pattern.py` rather than a `cdl.py` of its own, so it is not a `Category` entry and no existing `__getattr__` branch matched it. Restored next to the `ALL_PATTERNS` branch that exists for the same reason, and added to `__dir__()`. It is the same object as `ta.candles.cdl`. `ta.cdl_pattern` and `df.ta.cdl_pattern` were never affected, and `df.ta.cdl` has never existed — the accessor only ever exposed `cdl_doji`, `cdl_inside`, `cdl_pattern` and `cdl_z`.

The new test fails against `main`'s `__init__.py` (verified by stashing the change). Gates still clean: `pytest tests/test_lazy_core.py tests/test_accessor_api.py tests/test_indicator_candle.py` → 56 passed, black 317 unchanged, ruff clean, mypy 316 files clean.
